# Generated by Django 4.2.3 on 2023-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTempalteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_item_short_text', models.TextField()),
                ('template_item_long_text', models.TextField()),
                ('checklist_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
