# Generated by Django 4.2.3 on 2023-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0002_checklisttempalteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttempalteitems',
            name='order',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='checklisttempalteitems',
            name='template_item_long_text',
            field=models.TextField(null=True),
        ),
    ]
