# Generated by Django 4.2.3 on 2023-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0003_checklisttempalteitems_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttempalteitems',
            old_name='order',
            new_name='sort_order',
        ),
    ]
