# Generated by Django 4.2.3 on 2023-08-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0004_rename_order_checklisttempalteitems_sort_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistTempalteItems',
            new_name='ChecklistTemplateItems',
        ),
    ]
