# Generated by Django 4.2.3 on 2023-08-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0006_checklisttemplateitems_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplateitems',
            name='checklist_id',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitems',
            name='owner',
        ),
        migrations.AddField(
            model_name='checklisttemplateitems',
            name='source_checklist',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='checklist_manager.sourcechecklist'),
            preserve_default=False,
        ),
    ]
