# Generated by Django 4.2.3 on 2023-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('startdate', models.DateTimeField()),
                ('completeddate', models.DateTimeField()),
                ('iscomplete', models.BooleanField(default=False)),
            ],
        ),
    ]
