# Generated by Django 4.2.3 on 2023-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checklist_completeddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='source',
        ),
        migrations.AddField(
            model_name='checklist',
            name='assigned_to_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_id',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_item_long_text',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_item_short_text',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_item_users_notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='sort_order',
            field=models.IntegerField(default=99),
        ),
    ]
