# Generated by Django 4.2.3 on 2023-08-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_manager', '0005_rename_checklisttempalteitems_checklisttemplateitems'),
        ('checklist', '0003_remove_checklist_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='assigned_to_user_id',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_id',
        ),
        migrations.CreateModel(
            name='ChecklistHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_user_id', models.IntegerField()),
                ('checklist_custom_title', models.TextField()),
                ('checklist_notes', models.TextField()),
                ('checklist_startdate', models.DateTimeField(null=True)),
                ('checklist_completed_date', models.DateTimeField(null=True)),
                ('checklist_iscomplete', models.BooleanField(default=False)),
                ('source_checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist_manager.sourcechecklist')),
            ],
        ),
    ]
