# Generated by Django 4.2.3 on 2023-09-25 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(null=True)),
                ('feedback_date_time', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 6, 21, 57, 654883))),
                ('user_giving_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_giving_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
