# Generated by Django 4.2.3 on 2023-09-26 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 4, 55, 22, 817062)),
        ),
    ]
