# Generated by Django 4.2.3 on 2023-10-03 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_feedback_feedback_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
