# Generated by Django 4.2.3 on 2023-08-30 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
