# Generated by Django 4.2.3 on 2023-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='days_until_account_expiry',
            field=models.IntegerField(default=14),
        ),
    ]
