# Generated by Django 4.2.3 on 2023-09-15 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customer_days_until_account_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 6, 35, 35, 343700)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(null=True, unique=True),
        ),
    ]
