# Generated by Django 4.2.3 on 2023-09-22 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_userstocustomerrelationship_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 7, 5, 48, 6, 95644)),
        ),
        migrations.AlterField(
            model_name='userstocustomerrelationship',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='customers.customer'),
        ),
    ]
