# Generated by Django 4.2.3 on 2023-09-22 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0012_alter_customer_account_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 7, 6, 8, 28, 278079)),
        ),
        migrations.AlterField(
            model_name='userstocustomerrelationship',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='userstocustomerrelationship',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstocustomerrelationship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
