# Generated by Django 4.2.3 on 2023-09-25 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_account_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 6, 21, 57, 650370)),
        ),
    ]
