# Generated by Django 4.2.3 on 2023-09-26 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0015_alter_customer_account_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 11, 4, 55, 22, 817062)),
        ),
        migrations.AlterField(
            model_name='userstocustomerrelationship',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
