# Generated by Django 4.2.3 on 2023-10-03 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_account_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 18, 5, 54, 26, 151087)),
        ),
    ]
